---
pagetitle: CV
output:
  html_document:
    fig_width: 1
---

[Download CV as pdf.](files/CV_KULD_Lukas.pdf)

<style>
.cv-table { width: 100%; border: none; border-collapse: collapse; margin-bottom: 1em; }
.cv-table td { vertical-align: top; border: none; padding: 2px 8px 2px 0; }
.cv-table td:first-child { width: 70%; }
.cv-table td:last-child { width: 30%; white-space: nowrap; text-align: right; }
</style>

### Employment

<table class="cv-table"><tr>
<td>**University of Limerick**<br>Lecturer, Department of Economics, Kemmy Business School<br>Limerick, Ireland</td>
<td>Since 2022</td>
</tr></table>

<table class="cv-table"><tr>
<td>**TU Dortmund**<br>Postdoctoral Researcher, Chair of Urban, Regional, and International Economics, Department of Economics<br>Dortmund, Germany</td>
<td>2017--2021</td>
</tr></table>

### Education

<table class="cv-table"><tr>
<td>**Trinity College Dublin**<br>Ph.D. Economics<br>Dissertation: "Research collaboration and dissemination in economics"<br>Advisor: John O'Hagan; Committee: Christian Fons-Rosen, Carol Newman<br>Dublin, Ireland</td>
<td>2013--2018</td>
</tr></table>

<table class="cv-table"><tr>
<td>**ENSAE Paris**<br>Statistician-Economist (~M.Sc. grande école programme)<br>Paris, France</td>
<td>2010--2013</td>
</tr></table>

<table class="cv-table"><tr>
<td>**University of Mannheim**<br>M.Sc. Economics<br>B.Sc. Economics (Minor in Mathematics)<br>Mannheim, Germany</td>
<td>2011--2013<br>2008--2011</td>
</tr></table>

### Honours & Awards

<table class="cv-table"><tr>
<td>**Government of Ireland Postgraduate Scholarship**<br>Irish Research Council</td>
<td>2014--2017</td>
</tr></table>

<table class="cv-table"><tr>
<td>**Department Scholarship**<br>Department of Economics, Trinity College Dublin</td>
<td>2013--2017</td>
</tr></table>

<table class="cv-table"><tr>
<td>**ENSAE-Mannheim double degree scholarship**<br>Franco-German University (UFA-DFH)</td>
<td>2010--2013</td>
</tr></table>

### Computer skills & languages

**Statistics:** R (fluent), working knowledge of Stata, SAS, Matlab, Python

**Languages:** English (fluent), French (proficient), German (native)

### Conference presentations

PUCK Bilbao (2014), EWACE Vienna (2015), ACEI Valladolid (2016), RGS Dortmund (2017), JME Le Mans (2017), EEA-ESEM Cologne (2018), EWACE Copenhagen (2019), ACEI Lille (2021), Uni Limerick (department seminar) 2022, IEA Limerick 2022, Uni Portsmouth (department seminar) 2022, EWACE Turin 2022, Uni Maynooth (department seminar) 2023, ACEI Bloomington 2023, RSA Florence 2024, PARTNER Strasbourg 2025, IEA Thurles (2026)

### References

- Christiane Hellmanzik, Professor of Urban, Regional and International Economics, Technical University of Dortmund, Germany
- John O'Hagan, Professor of Economics (Emeritus), Department of Economics, Trinity College Dublin, Ireland
- Carol Newman, Professor in Economics, Department of Economics, Trinity College Dublin, Ireland